branches:
  except:
    - docs
    - gh-pages

sudo: required

services:
  - docker

install:
  - echo "ENV HOHO ${API_KEY}" >> Dockerfile
  - echo "ENV COVERALLS_REPO_TOKEN ${COVERALLS_REPO_TOKEN}" >> Dockerfile
  - echo "ENV TRAVIS_BRANCH ${TRAVIS_BRANCH}" >> Dockerfile
  - echo "ENV TRAVIS_JOB_ID ${TRAVIS_JOB_ID}" >> Dockerfile
  - echo "ENV CI ${CI}" >> Dockerfile
  - echo "ENV TRAVIS ${TRAVIS}" >> Dockerfile
  - docker-compose up --build -d

script:
  - docker exec -it foodcare-api bash -c 'echo "$HOHO"'
  - docker exec -it foodcare-api coverage run manage.py test

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $API_KEY
  app:
    master: food-care
    develop: foodcarehomol
  run:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
 

after_script:
  - docker-compose down --remove-orphans
