branches:
  except:
    - docs
    - gh-pages

sudo: required

services:
  - docker

install:
  - echo "ENV HOHO ${API_KEY}" >> Dockerfile
  - echo "ENV COVERALLS_REPO_TOKEN ${COVERALLS_REPO_TOKEN}" >> Dockerfile
  - echo "ENV TRAVIS_BRANCH ${TRAVIS_BRANCH}" >> Dockerfile
  - echo "ENV TRAVIS_JOB_ID ${TRAVIS_JOB_ID}" >> Dockerfile
  - echo "ENV CI ${CI}" >> Dockerfile
  - echo "ENV TRAVIS ${TRAVIS}" >> Dockerfile
  - docker-compose up --build -d

script:
  - docker exec -it foodcare-api bash -c 'echo "$HOHO"'
  - docker exec -it foodcare-api coverage run manage.py test

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: IfyExGKTlWqObVWAMxG9h/WyshnzguOX9uZnvDXgH5PRsAca7Be25X5SVR0SQY8gkfGetYls44Y6ECyRkFABCazM+kpIIpkj/CgbHqexff0Ppz1ywX/69vegiuPpsOgH0xw/BVrVQ+2ex9sweZxeruL4Fr+l2KY5RnYqHIAiiLSY+4oXPOIpeMzNg3JH5ekon2ltYbfMT2PrGm7AJdlO1RpK0e1vnDKDxu0pfpNDl9HdPSPUdLqgLgdM2eBnN/votcQy3Qq4urLoUPfF3eqC5mkziag2m5jxWDC7KnuTnARaZcx5gCKdZAKq/ZdFQ8T8K76KiU23GU2WWc2ZnjFNqBsynigfx4Y763cdBW6Is/edYXS9I/R7pCd2C/rOpRVz69BSzs6pSUQMFsk1JV55Q4jYbU9KAw8QC/A4iInYTgH5/0YrrLdRfpAkDCBIB8Hrq8GCsf08a7JcS6miX3lMSNvjb+orFFz9ClmCaP+jZZ0v7u2P7J2UDDj/eJ9SnqsIF/vHIXNRNednk+bQsWHpNI/keTujgcxClq4sgAnulWJih3YUXBNZWArXp+sF/OZpvaRIa1XcJDTVch+bFnjdaqohlhUIsHmOZmuvj+Rv94/5h4rYZaoED3HibOi4VcjREREbwAIkLM0sHlrNKEMVwpHo25y77Uhh9sXqWPU+DpI=
  app:
    master: food-care
    develop: foodcarehomol
  run:
  - python3 manage.py makemigrations
  - python3 manage.py migrate
 

after_script:
  - docker-compose down --remove-orphans
